-- CapDent pricing V2 foundation for Android version 18.
--
-- Production safety guarantees:
--   * additive database objects only
--   * no existing table, column, function, or RLS policy is removed or renamed
--   * no trigger is added to public.patients
--   * no patient insert can be rejected by this migration
--   * every rollout flag starts disabled
--   * every clinic existing when this migration runs is grandfathered
--   * new clinics receive a non-enforcing pricing settings row
--
-- Review and validate this migration on a Supabase development branch before
-- applying it to the production project.

begin;

create table if not exists public.capdent_plan_catalog (
  code text primary key,
  display_name text not null,
  monthly_price numeric(10, 2) not null default 0 check (monthly_price >= 0),
  patient_limit integer check (patient_limit is null or patient_limit > 0),
  storage_limit_bytes bigint not null check (storage_limit_bytes > 0),
  analytics_enabled boolean not null default false,
  multi_clinic_enabled boolean not null default false,
  clinic_limit integer not null default 1 check (clinic_limit > 0),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint capdent_plan_catalog_code_check
    check (code in ('free', 'cloud', 'intelligence'))
);

create table if not exists public.capdent_pricing_flags (
  key text primary key,
  enabled boolean not null default false,
  description text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.clinic_pricing_settings (
  clinic_id uuid primary key references public.clinics(id) on delete cascade,
  pricing_policy_version integer not null default 1 check (pricing_policy_version > 0),
  patient_limit_enforced boolean not null default false,
  grandfathered boolean not null default true,
  intelligence_enabled_override boolean,
  multi_clinic_enabled_override boolean,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Reserved for a later observation-only rollout. Nothing writes to this table
-- in this migration and no patient trigger is created.
create table if not exists public.capdent_pricing_shadow_events (
  id bigint generated by default as identity primary key,
  clinic_id uuid not null references public.clinics(id) on delete cascade,
  profile_id uuid references public.profiles(id) on delete set null,
  app_platform text,
  app_version text,
  patient_count integer not null check (patient_count >= 0),
  plan_code text not null,
  would_block boolean not null,
  observed_at timestamptz not null default now()
);

create or replace function public.set_capdent_pricing_updated_at()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists capdent_plan_catalog_updated_at on public.capdent_plan_catalog;
create trigger capdent_plan_catalog_updated_at
before update on public.capdent_plan_catalog
for each row execute function public.set_capdent_pricing_updated_at();

drop trigger if exists capdent_pricing_flags_updated_at on public.capdent_pricing_flags;
create trigger capdent_pricing_flags_updated_at
before update on public.capdent_pricing_flags
for each row execute function public.set_capdent_pricing_updated_at();

drop trigger if exists clinic_pricing_settings_updated_at on public.clinic_pricing_settings;
create trigger clinic_pricing_settings_updated_at
before update on public.clinic_pricing_settings
for each row execute function public.set_capdent_pricing_updated_at();

insert into public.capdent_plan_catalog (
  code,
  display_name,
  monthly_price,
  patient_limit,
  storage_limit_bytes,
  analytics_enabled,
  multi_clinic_enabled,
  clinic_limit,
  active
)
values
  ('free', 'Free', 0, 300, 1073741824, false, false, 1, true),
  ('cloud', 'CapDent Cloud', 799, null, 5368709120, false, false, 1, true),
  ('intelligence', 'CapDent Intelligence', 1499, null, 21474836480, true, true, 3, true)
on conflict (code) do update
set
  display_name = excluded.display_name,
  monthly_price = excluded.monthly_price,
  patient_limit = excluded.patient_limit,
  storage_limit_bytes = excluded.storage_limit_bytes,
  analytics_enabled = excluded.analytics_enabled,
  multi_clinic_enabled = excluded.multi_clinic_enabled,
  clinic_limit = excluded.clinic_limit,
  active = excluded.active,
  updated_at = now();

insert into public.capdent_pricing_flags (key, enabled, description)
values
  ('pricing_v2_visible', false, 'Show the V2 pricing and usage experience in supported clients.'),
  ('patient_limit_shadow_mode', false, 'Calculate would-block outcomes without rejecting patient inserts.'),
  ('patient_limit_enforcement', false, 'Allow a future V2 server function to reject patient 301 for explicitly enabled, non-grandfathered clinics.'),
  ('intelligence_enabled', false, 'Release the Intelligence analytics entitlement.'),
  ('multi_clinic_enabled', false, 'Release multi-clinic owner functionality.')
on conflict (key) do update
set
  description = excluded.description,
  updated_at = now();

-- Every clinic that exists at migration time is permanently grandfathered by
-- default and remains non-enforcing unless a later reviewed migration changes
-- that clinic deliberately.
insert into public.clinic_pricing_settings (
  clinic_id,
  pricing_policy_version,
  patient_limit_enforced,
  grandfathered
)
select
  c.id,
  1,
  false,
  true
from public.clinics c
on conflict (clinic_id) do nothing;

-- Future clinics get their own settings row without changing the existing
-- create_owner_clinic functions. Enforcement still starts false.
create or replace function public.initialize_capdent_pricing_for_new_clinic()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  insert into public.clinic_pricing_settings (
    clinic_id,
    pricing_policy_version,
    patient_limit_enforced,
    grandfathered
  )
  values (
    new.id,
    1,
    false,
    false
  )
  on conflict (clinic_id) do nothing;

  return new;
end;
$$;

revoke all on function public.initialize_capdent_pricing_for_new_clinic() from public;

drop trigger if exists clinics_initialize_capdent_pricing on public.clinics;
create trigger clinics_initialize_capdent_pricing
after insert on public.clinics
for each row execute function public.initialize_capdent_pricing_for_new_clinic();

alter table public.capdent_plan_catalog enable row level security;
alter table public.capdent_pricing_flags enable row level security;
alter table public.clinic_pricing_settings enable row level security;
alter table public.capdent_pricing_shadow_events enable row level security;

drop policy if exists capdent_plan_catalog_authenticated_read on public.capdent_plan_catalog;
create policy capdent_plan_catalog_authenticated_read
on public.capdent_plan_catalog
for select
to authenticated
using (active = true);

drop policy if exists capdent_pricing_flags_authenticated_read on public.capdent_pricing_flags;
create policy capdent_pricing_flags_authenticated_read
on public.capdent_pricing_flags
for select
to authenticated
using (true);

drop policy if exists clinic_pricing_settings_same_clinic_read on public.clinic_pricing_settings;
create policy clinic_pricing_settings_same_clinic_read
on public.clinic_pricing_settings
for select
to authenticated
using (clinic_id = public.current_clinic_id());

-- Application clients can read pricing state but cannot directly modify plan
-- authority, feature flags, per-clinic enforcement, or shadow audit records.
revoke all on public.capdent_plan_catalog from anon, authenticated;
revoke all on public.capdent_pricing_flags from anon, authenticated;
revoke all on public.clinic_pricing_settings from anon, authenticated;
revoke all on public.capdent_pricing_shadow_events from anon, authenticated;

grant select on public.capdent_plan_catalog to authenticated;
grant select on public.capdent_pricing_flags to authenticated;
grant select on public.clinic_pricing_settings to authenticated;

create or replace function public.get_capdent_entitlements_v2()
returns jsonb
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
declare
  v_clinic_id uuid;
  v_subscription public.clinic_subscriptions%rowtype;
  v_plan public.capdent_plan_catalog%rowtype;
  v_settings public.clinic_pricing_settings%rowtype;
  v_legacy_plan text := 'free';
  v_plan_code text := 'free';
  v_patient_count integer := 0;
  v_storage_used_bytes bigint := 0;
  v_pricing_visible boolean := false;
  v_shadow_mode boolean := false;
  v_global_enforcement boolean := false;
  v_intelligence_released boolean := false;
  v_multi_clinic_released boolean := false;
  v_effective_enforcement boolean := false;
  v_can_add_patient boolean := true;
  v_would_block boolean := false;
  v_remaining integer;
  v_analytics_enabled boolean := false;
  v_multi_clinic_enabled boolean := false;
begin
  if auth.uid() is null then
    raise exception 'Login required';
  end if;

  v_clinic_id := public.current_clinic_id();
  if v_clinic_id is null then
    raise exception 'Clinic profile not found';
  end if;

  select count(*)::integer
  into v_patient_count
  from public.patients p
  where p.clinic_id = v_clinic_id;

  select *
  into v_subscription
  from public.clinic_subscriptions cs
  where cs.clinic_id = v_clinic_id
  limit 1;

  if found then
    v_legacy_plan := lower(coalesce(v_subscription.plan_name, 'free'));

    if lower(coalesce(v_subscription.status, 'free')) in ('active', 'grace_period')
       and lower(coalesce(v_subscription.google_play_status, 'not_started'))
         not in ('cancelled', 'expired', 'account_hold') then
      v_plan_code := case
        when v_legacy_plan in ('clinic_intelligence', 'intelligence') then 'intelligence'
        when v_legacy_plan in ('professional', 'google_play_monthly', 'cloud') then 'cloud'
        else 'free'
      end;
    end if;
  end if;

  select *
  into v_plan
  from public.capdent_plan_catalog pc
  where pc.code = v_plan_code
    and pc.active = true
  limit 1;

  if not found then
    select *
    into v_plan
    from public.capdent_plan_catalog pc
    where pc.code = 'free'
    limit 1;
    v_plan_code := 'free';
  end if;

  select *
  into v_settings
  from public.clinic_pricing_settings cps
  where cps.clinic_id = v_clinic_id
  limit 1;

  select coalesce((select enabled from public.capdent_pricing_flags where key = 'pricing_v2_visible'), false)
  into v_pricing_visible;

  select coalesce((select enabled from public.capdent_pricing_flags where key = 'patient_limit_shadow_mode'), false)
  into v_shadow_mode;

  select coalesce((select enabled from public.capdent_pricing_flags where key = 'patient_limit_enforcement'), false)
  into v_global_enforcement;

  select coalesce((select enabled from public.capdent_pricing_flags where key = 'intelligence_enabled'), false)
  into v_intelligence_released;

  select coalesce((select enabled from public.capdent_pricing_flags where key = 'multi_clinic_enabled'), false)
  into v_multi_clinic_released;

  -- Three independent conditions are required. Existing/missing clinic settings
  -- fail open because grandfathered defaults to true here.
  v_effective_enforcement :=
    v_global_enforcement
    and coalesce(v_settings.patient_limit_enforced, false)
    and not coalesce(v_settings.grandfathered, true);

  if v_plan.patient_limit is null then
    v_remaining := null;
    v_would_block := false;
  else
    v_remaining := greatest(v_plan.patient_limit - v_patient_count, 0);
    v_would_block := v_patient_count >= v_plan.patient_limit;
  end if;

  -- This read-only function reports whether a future server mutation would be
  -- allowed. It does not perform or reject any patient insert itself.
  v_can_add_patient := not v_effective_enforcement or not v_would_block;

  v_analytics_enabled :=
    v_plan.analytics_enabled
    and v_intelligence_released
    and coalesce(v_settings.intelligence_enabled_override, true);

  v_multi_clinic_enabled :=
    v_plan.multi_clinic_enabled
    and v_multi_clinic_released
    and coalesce(v_settings.multi_clinic_enabled_override, true);

  -- Supabase Storage objects currently use clinic_id as the first path segment.
  -- Older/non-matching objects are ignored rather than affecting access.
  select coalesce(
    sum(
      case
        when so.metadata is not null
          and so.metadata ? 'size'
          and (so.metadata ->> 'size') ~ '^[0-9]+$'
        then (so.metadata ->> 'size')::bigint
        else 0
      end
    ),
    0
  )
  into v_storage_used_bytes
  from storage.objects so
  where split_part(so.name, '/', 1) = v_clinic_id::text;

  return jsonb_build_object(
    'version', 2,
    'clinicId', v_clinic_id,
    'legacyPlanName', v_legacy_plan,
    'plan', v_plan_code,
    'planLabel', v_plan.display_name,
    'monthlyPrice', v_plan.monthly_price,
    'patientCount', v_patient_count,
    'patientLimit', v_plan.patient_limit,
    'remainingPatients', v_remaining,
    'canAddPatient', v_can_add_patient,
    'wouldBlockAtCurrentCount', v_would_block,
    'patientLimitEnforced', v_effective_enforcement,
    'shadowMode', v_shadow_mode,
    'pricingVisible', v_pricing_visible,
    'storageUsedBytes', v_storage_used_bytes,
    'storageLimitBytes', v_plan.storage_limit_bytes,
    'analyticsEnabled', v_analytics_enabled,
    'multiClinicEnabled', v_multi_clinic_enabled,
    'clinicLimit', v_plan.clinic_limit,
    'grandfathered', coalesce(v_settings.grandfathered, true),
    'pricingPolicyVersion', coalesce(v_settings.pricing_policy_version, 1),
    'subscriptionStatus', coalesce(v_subscription.status, 'free'),
    'currentPeriodEnd', v_subscription.current_period_end
  );
end;
$$;

revoke all on function public.get_capdent_entitlements_v2() from public;
grant execute on function public.get_capdent_entitlements_v2() to authenticated;

comment on function public.get_capdent_entitlements_v2() is
  'Read-only, disabled-by-default CapDent pricing V2 entitlement snapshot. It does not enforce patient limits.';

commit;
